### ISSUE TITLE
miv: Parse error

### ISSUE THREAD

**Issue by kozo2** [itchyny/miv#2]
# error message

```
~/.cabal/bin% ./miv update
miv: Parse error

```
# how to reproduce error
- vim-jp配付 macvim latest
- mac os x 10.9.4
- brewでinstallしたhaskell-platform latest
- miv commit eeb6dca85df7d0fc6c6ef65a039a686db52cdeeb

.vimrc.yaml

```
config: {}
plugin:
  Valloric/YouCompleteMe:
    submodule: true
    command:
      - YcmCompleter 
```

.vim/vimrc

```
filetype off
if has('vim_starting')
  set rtp^=~/.vim/miv/miv/
endif
filetype plugin indent on

nnoremap ; :
nnoremap : ;

```
